Feature/play videos like reels
guruprasadDev/Instagram pull request #9
Opened 2022-11-04 05:32 UTC by guruprasadDev

Implementing reels on Instagram clone

2022-11-09 06:39 UTC, subirMM commented on app/src/main/java/com/guruthedev/instagram/AccountSettingsActivity.kt
> +            val intent = Intent(this, PassingData::class.java)
use scope function properly for intent and binding

2022-11-09 06:41 UTC, subirMM commented on app/src/main/res/layout/activity_account_settings.xml
> +            android:text="@string/add_btn"
please rename add_btn to something else

2022-11-09 06:49 UTC, subirMM commented on app/src/main/java/com/guruthedev/instagram/AccountSettingsActivity.kt
> +        binding.apply {
can we try using scope function properly for resultData and binding

2022-11-16 10:29 UTC, mm-aman commented on app/src/main/java/com/guruthedev/instagram/ui/fragments/ProfileFragment.kt
>  }
I see "No new line at end of file" warning with many files. Please add new line.

2022-11-16 10:31 UTC, mm-aman commented on app/src/main/java/com/guruthedev/instagram/utils/VerifyInternetConnection.kt
> +            Log.d(TAG, "onAvailable: $network")
remove logs before pushing code

2022-11-16 10:33 UTC, mm-aman commented on app/src/main/java/com/guruthedev/instagram/utils/VerifyInternetConnection.kt
> +                CoroutineScope(Dispatchers.IO).launch {
do we really need a coroutine scope here ?

2022-11-16 10:35 UTC, mm-aman commented on app/src/main/res/layout/video_list_item.xml
> +            app:layout_constraintHorizontal_bias="0.0"
avoid using **constraintHorizontal_bias](app:layout_constraintHorizontal_bias="0.0"**

2022-11-16 10:37 UTC, mm-aman commented on app/src/main/java/com/guruthedev/instagram/ui/fragments/PostFragment.kt
> +                    "The camera permission is necessary",
please move this string to string.xml

2022-11-16 10:38 UTC, mm-aman requested changes
Pointed few minor issues. Please look out on them. 
Overall looks good to me.

2022-11-17 07:09 UTC, subirMM approved these changes

2022-11-17 07:10 UTC, merged